title: Just the Docs
description: Me starting a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mklimek1.github.io/fantastic-guacamole

aux_links:
  Template Repository: https://github.com/mklimek1/fantastic-guacamole
